### ISSUE TITLE
reStructuredText

### ISSUE THREAD

**Issue by cup** [nifty-site-manager/nsm#12]
I see that Markdown is supported:

https://www.nift.cc/docs/markdown.html

Is reStructuredText supported?

https://docutils.sourceforge.io/docs/user/rst/quickref.html

**Comment by n-ham** [comment]
First time I've heard of reStructuredText but from what I can work out I think it should be possible. If you can convert something to html from the command line then you can use it with Nift, and it sounds like you should be able to use Docutils to convert reStructuredText to html? 

You can use `@system{inject}(sys-call)` to inject the output of running `sys-call`. Eg. to use pandoc to convert a markdown file to html you can use `@system{inject}(pandoc file-path)` so it will be similar to that with docutils and reStructuredText hopefully.

Nift also parses the output text of the system call with Nift's template language, so you should be able to use Nift's template language in your reStructuredText (including breaking up your reStructuredText in to multiple files, just put `@system{inject}(docutil command)` calls inside the files with reStructuredText. 

Let me know if any of that doesn't make sense. Would love to know how you go if you do try it out. I am currently working on adding programming language features to the template language.

**Comment by n-ham** [comment]
It looks like pandoc might even support reStructuredText, so you can probably even use that to pre-render rst to html with Nift as well.
