### ISSUE TITLE
MarkDown

### ISSUE THREAD

**Issue by cup** [nifty-site-manager/nsm#13]
So I see that MarkDown is possible:

https://nifty-site-manager.com/docs/markdown

but its not clear how to actually make it work. I see this:

~~~
@system{inject}("pandoc file-path")
~~~

but it doesnt say where you would put that code. I also see this:

https://github.com/nifty-site-manager/simple-site

but Im not sure what to make of it. Im guessing a layout like this would be
needed?

~~~
content/
   sunday.content
   sunday.md
~~~

then put the inject inside the content file? That just seems strange because
then you need 2 files for every post. I think I am not understanding it.

**Comment by n-ham** [comment]
You can put `@system{inject}("pandoc file-path")` in any of the files in the `content/` or `template/` directories. 

Another way to convert markdown rather than pre-rendering it at build time is to use javascript libraries to do it at load time. This is done with the markdown-blog template for example, check the source code of https://nsm-blogs.github.io/markdown-blog/blog/post01.html and https://gitlab.com/nsm-blogs/markdown-blog (the gitlab templates have all files in one branch, whereas github/bitbucket had the files in 2 different branches because of how github/bitbucket pages work, you can import the gitlab templates to github/bitbucket if you want to for example hook netlify up to a repo on github/bitbucket and have netlify build the site on their servers, just chuck the ubuntu nift binary from github releases in the repo and have netlify use that). 

You can find more templates at https://www.nift.cc/resources/templates.html and https://www.nift.cc/resources/blog_templates.html.

Alternatively to the layout structure you suggested, you can set the content extension site wide using `nsm new-cont-ext .md` or for specific pages using `nsm new-cont-ext page-name .md` then in `template/page.template` (or whatever template you are using for injecting markdown files into) replace `@content()` with `@system{content}(pandoc)`. Then you only need one markdown file for each post. 

I actually quite like using Showdown to convert at load time. You can just have markdown blocks in between html code, plus it scales much better because pre-rendering at load time aggregates the time that takes, whereas converting at load time is done on a page-by-page basis.

**Comment by n-ham** [comment]
Soon Nift will even have if/else-if/else statements etc. so you will even be able to do something like the following in `template/page.template`

@if(@==(@[cont-ext], ".md"))
    @system{content}(pandoc)
@else
    @content()

So you can use the same template file for different kinds of content files.

**Comment by cup** [comment]
@n-ham that doesnt seem to work:

~~~
$ nsm-fix clone https://github.com/nsm-templates/simple-site.git
$ cd simple-site
$ nsm-fix rm about
successfully removed about

$ nsm-fix rm index
successfully removed index

$ nsm-fix new-cont-ext .md
successfully changed content extension to '.md'

$ mkdir content
$ echo 'hello world' > content/sunday.md
$ nsm-fix build-all
all 0 output files built successfully
time taken: 0 seconds
~~~

**Comment by n-ham** [comment]
You have to either track the file manually using eg. `nsm track sunday` then `nsm build-all`.

Or if you want Nift to pick up the existence of content files in `content/` automatically add `nsm watch content/ .md" (you should even be able to do just `nsm watch content/` when .md is the default content extension.

**Comment by cup** [comment]
Still no luck:

~~~
$ nsm-fix clone https://github.com/nsm-templates/simple-site.git
$ cd simple-site
$ nsm-fix watch content/ .md
successfully watching directory 'content/' with:
  content extension: '.md'
      template path: 'template/page.template'
   output extension: '.html'

$ echo 'hello world' > content/sunday.md
$ nsm-fix build-all
error: watched content extensions file '.nsm/.watchinfo/content|.exts' does not
exist for watched directory
error: failed to open watch list '.nsm/.watchinfo/watching.list'
~~~

**Comment by n-ham** [comment]
Ah okay, I had been replacing '/' and '\' in the directory path for watching with '|' for use in the filename, however it appears that you cannot have '|' in filenames on Windows. I will figure something else out and fix. Thanks heaps for identifying these Windows bugs and pointing them out, some people problem come across them and pass on Nift without even reporting them.

**Comment by n-ham** [comment]
I've got some Nift stickers too, if you would like me to send you some for free just email me your postal address and name to `contact@n-ham.com`.

**Comment by cup** [comment]
If you have a `THANKS` file or similar, I wouldnt mind being on that

https://en.wikipedia.org/wiki/README#As_a_generic_term

**Comment by n-ham** [comment]
I will add something of the sort, I need to add a contributors file as well (might even put bug hunters in that maybe). Do you want to be listed as `cup`, `Steven Penny` or both?

**Comment by cup** [comment]
Maybe something like this:

Steven Penny (github.com/cup)

**Comment by n-ham** [comment]
I should be able to make your name a link even. I've fixed the watch bug, I will let you know when I've updated `nsm-fix.exe` on the github release. Happy to send stickers as well :)

**Comment by cup** [comment]
I am pretty picky about the software I use, so I dont know if Nift will
ultimately work out for me. But I like everything Ive seen so far, so I figured
its fair that I should report an issue if I see it.

Then if it doesnt get fixed, at least I tried, and if it does get fixed, all the
better.

**Comment by n-ham** [comment]
I can understand if you're hesitant based on the number of bugs that are popping up here for Windows. I will get straight on to fixing any bugs that arise.

**Comment by cup** [comment]
I dont mind bugs, if I can fix them myself or the owner is open to fixing. I am
using Hugo curretly but looking for a replacement.

**Comment by n-ham** [comment]
I am curious why you're looking for a replacement for Hugo?

I just noticed there's a file I'm not updating (and removing if needed) when unwatching, so going to fix that as well.

**Comment by cup** [comment]
> I am curious why you're looking for a replacement for Hugo?

My use case is sometimes I have long links, like this:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/lastIndexOf

Ideally I would like to split the link in the markup like this:

~~~
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/
Global_Objects/String/lastIndexOf
~~~

but MarkDown doesnt support that:

https://github.com/commonmark/commonmark-spec/issues/631

other markups like reStructuredText do support it, but most site generators only
support MarkDown. The other option is to use the site generator templates. Hugo
uses Go templates, which appear to not support multiple lines:

https://github.com/gohugoio/hugo/issues/6726

So I am looking for either a site generator with reStructuredText support, or a
site generator whose templates support multiple lines. I think JigSaw works for
my use case, so I have been looking at that as well:

https://github.com/tightenco/jigsaw

**Comment by n-ham** [comment]
The functionality doesn't quite work yet, but you should be able to do it with just Nift using 

    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/@!\n
    Global_Objects/String/lastIndexOf

It will work currently without any indenting on the second line, but if there's indenting there currently that will show up there `@!\n` starts. But I think it would be a good idea to have `@!\n` skip to the first non-whitespace following it. Or I could leave the functionality for that as is and add something else to skip to the next non-whitespace (including skipping over newlines). That would do what you want without having to use rst. Any suggestions on nice short syntax to skip to the next non-whitespace?

**Comment by n-ham** [comment]
Jigsaw actually looks quite similar to Nift? I wonder if it's anywhere near as fast as Hugo or even better Nift? You may not care about scaling websites up to millions or hundreds of thousands of pages though.

**Comment by n-ham** [comment]
I changed to having all multi-line comments putting the first non-whitespace text following the comment where the comment started recently, but think that might not be a good idea for all of them. It works awesomely most of the time except at the end of an indented block. For example:

    <tag>
        code

        @/*
            multi-line comment
        @*/
    <tag>

Doing that then leads to: 

    <tag>
        code

        <tag>

In the output file, which is not what one wants.

**Comment by cup** [comment]
> Any suggestions on nice short syntax to skip to the next non-whitespace?

Ideally no characters would be between the two parts other than whitespace. So
that means one of these:

~~~
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/
Global_Objects/String/lastIndexOf

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/
   Global_Objects/String/lastIndexOf
~~~

Personally if the space character is not allowed and only newline works, I am
fine with that, but I dont want extra characters other than newline or space
if possible. AsciiDoc uses this syntax to deal with that:

~~~
link:++https://developer.mozilla.org/docs/Web/JavaScript/Reference/
Global_Objects/String/lastIndexOf++[LINK TEXT]
~~~

and some site generator template use strings, where the language supports
multiline strings, so something like:

~~~
@link("https://developer.mozilla.org/docs/Web/JavaScript/Reference/
Global_Objects/String/lastIndexOf")
~~~

> Jigsaw actually looks quite similar to Nift? I wonder if it's anywhere near as
> fast as Hugo or even better Nift?

From my experience its pretty darn fast. It was rendering an example site in
0.1 second, but that was only like 10 pages.

> You may not care about scaling websites up to millions or hundreds of
> thousands of pages though.

Yeah my biggest site is only like 100 pages currently, will maybe top out at
200. So I dont need anything crazy.

**Comment by cup** [comment]
> I might leave `@--- comment @---` how it currently works (as above), but then
> go back to not skipping the trailing whitespace for `@/* comment @*/` and
> `<@-- comment --@>`. Would love to get opinions from other people on that..

The way Hugo (Go templates) handles this is like this:

~~~
{{ keep surrounding whitespace }}
{{ remove trailing whitespace -}}
{{- remove leading whitespace }}
{{- remove surrounding whitespace -}}
~~~

sometimes its mentally tricky as you dont want everything on one line, but I
think its a good syntax once you get used to it.

**Comment by n-ham** [comment]
0.1 seconds for 10 pages is slow if you ask me :). The Nift website has 36 pages including https://www.nift.cc/docs/content_files.html where the built page has 1431 lines. Nift can build the Nift website on my 2014 i5 macbook air running ubuntu in under 0.03s, so under 3/100ths of a second and under 1ms per page. 

I just added `@url(string)` to the template language. You can break input parameters for functions over several lines with leading indenting ignored. So you can now do:

    @url("https://developer.mozilla.org/docs/Web/JavaScript/Reference/
              Global_Objects/String/lastIndexOf")

Is that good enough? I'll finish fixing up unwatch then put the updated binary on github.

**Comment by n-ham** [comment]
I have no way to strip the leading whitespace because Nift literally parses each file once linearly (part of how it manages to be so incredibly fast). But I could try adding in syntax for skipping the trailing whitespace. I will try to think up something nice. If I add in something like `@!ws` you could do eg. `@/* comment @*/@!ws` but I think that's a bit too gross?

**Comment by n-ham** [comment]
Also should `@url(str)` just replace it with `str` so you have to do `<a href="@url(str)"></a>`, or I could even do `@url(str, txt)` and replace it with `<a href="str">txt</a>`. Maybe both? I can add options to the url function or just have different functions..

**Comment by n-ham** [comment]
I should add jigsaw to the nift vs. hugo pissing match ha :)

**Comment by cup** [comment]
~~~
@url("https://developer.mozilla.org/docs/Web/JavaScript/Reference/
   Global_Objects/String/lastIndexOf")
~~~

that looks great! will give it a try once the `watchinfo` thing is fixed.

> If I add in something like @!ws you could do eg. `@/* comment @*/@!ws` but I
> think that's a bit too gross?

honestly I would worry about it. When I was prototyping Hugo I did look closely
at the resultant HTML, but its probably a significant performance hit to deal
with leading whitespace.

If anything you could leave the default as is, then make an option for 2 pass
that removes leading whitespace for people who really care about that.

> Also should `@url(str)` just replace it with str so you have to do
> `<a href="@url(str)"></a>`

This use case is specifically for URLs, so given this input:

~~~
https://sunday.com/
monday
~~~

The result should be:

~~~
<a href="https://sunday.com/monday">https://sunday.com/monday</a>
~~~

or perhaps

~~~
<a href="https://sunday.com/monday">USER SUPPLIED STRING</a>
~~~

**Comment by n-ham** [comment]
Maybe I'll have `@str(txt)` so you could do `<a href="@str(txt)">whatever you want</a>`. Then have `@url(str)` and `@url(str, txt)` to be replaced with `<a href="str">str</a>` and `<a href="str">txt</a>`?

I think it would be good to have syntax to skip over whitespace whenever one wants to, I can add that cheaply. I just can't think of nice syntax for it. I don't even like `@!ws`.

**Comment by cup** [comment]
> Maybe I'll have `@str(txt)` so you could do
> `<a href="@str(txt)">whatever you want</a>`. Then have `@url(str)` and
> `@url(str, txt)` to be replaced with `<a href="str">str</a>` and
> `<a href="str">txt</a>`?

I would only do `@str(txt)` if you think theres a usecase for it outside of
links. I am not sure it would be useful, as its a function for essentially,
"given a (potentially multiline) string, remove any newlines". HTML already does
this. If you have this HTML:

~~~
<p>Sunday Monday
Tuesday</p>
~~~

You see this one the screen:

~~~
Sunday Monday Tuesday
~~~

but again, if you think its useful then by all means!

**Comment by n-ham** [comment]
I'm planning to add `@parse(str)` anyway which would be the same, so maybe I'll just do that. 

I could do `@->` for skipping whitespace, I think I like that more than `@!ws`.

**Comment by cup** [comment]
> I will probably keep `@--- comment @---` skipping trailing whitespace, but
> you'd then need to do eg. `@/* comment @*/@->` and `<@-- comment --@>@->` to
> skip whitespace after the other multiline coments.

That `@--- comment @---` is fine enough, but the other ones are hideous. If that
ends up being the syntax I would probably just not use it and deal with the
whitespace. If it helps, Hugo does it like this:

~~~
{{/* a comment */}}
{{- /* a comment with surrounding white space trimmed */ -}}
~~~

Also it appears that a Tab literal (or maybe 8 spaces) triggers a comment:

~~~
	A comment; discarded. May contain newlines.
	Comments do not nest and must start and end at the
	delimiters, as shown here.
~~~

https://golang.org/pkg/text/template#hdr-Actions

**Comment by n-ham** [comment]
What about `@->` in general to skip whitespace, but `@/* comment @*/-` `<@-- comment --@>-` for skipping trailing whitespace of comments? 

With 

    @if(condition)
    {
        block
    }

statements for example, if the condition is false so `block` isn't inserted/run then ideally you want it to skip the whitespace trailing the `}` for the `if` statement. However you run in to the same problem as above if the `if` statement is at the end of an indented block. I might have to add an option for if statements to optionally skip trailing whitespace if the condition fails, maybe `->`, wont be able to use `@->` as the option because by default options are parsed with the template language (as are parameters and function names).

**Comment by cup** [comment]
> However you run in to the same problem as above if the `if` statement is at
> the end of an indented block.

what you really need to worry about are loops. if someone has a huge loop with
few matches, then they are going to have a ton of extra newlines.

**Comment by n-ham** [comment]
The fixed version you have has early implementations of things like 

1. private and const variables, eg. `@:={private}(int, test.x=10)`. Then you can only change `x` from functions with `test.` at the start (and no more .'s), though you can still access the variable from anywhere.
2. user-defined functions 
    @funcdef(myFunc)
    {
        This is a function, the text is parsed and injected in to the page
        It adds a layer of scope to variables and defines variables like
        @[#no_params], @[#no_options], @[params[x]], @[options[x]]
       You can even do @funcdef{private}(myFunc)
    }

which can be called with

    @myFunc()

You can even do @myFunc{!s}() to not add scope, and @myFunc{!o}() to not inject the output to the page being built but parse it so programming stuff is processed.

**Comment by n-ham** [comment]
Loops and if statements etc. will definitely have a !o option to just process the statement/loop and not add output to the page. However ideally I need something else as well where normal text isn't injected to the page but you can manually inject text somehow. I can't think of any really easy ways to add that though, it's a bit messy changing things so I can.

**Comment by n-ham** [comment]
`@typedef(type-name)` will be coming as well.

**Comment by n-ham** [comment]
I have updated `nsm-fix.exe` on the github release. Watching directories should now be working on Windows (plus I found and fixed a few bugs with it generally). You should also be able to do `@link(url)` and `@link(url, link-txt)` where you can break `url` and `link-txt` up over several lines. Note that trailing whitespace on lines for parameters is included so you can add spaces/tabs at the end of the line, but leading whitespace on a new line with the same parameter is skipped.

**Comment by n-ham** [comment]
Still undecided about syntax to skip trailing whitespace for comments. Would you use `@/* comment @*/-` and `<@-- comment --@>-` or is that too gross?

**Comment by n-ham** [comment]
One option with comments is to have an actual function that can take options and parameters. Considering things like `@//(comment)`, `@/*(comment)` or `@%(comment)`.

Then I can have options like `!p` to not parse the comment text, and `!tws` for no trailing whitespace (open to suggestions for `!tws`). Eg. `@//{!tws}(comment)`. 

As parameters can be broken up over multiple lines one can then do multi line comments no worries. 

Thoughts? And any preferences on what the function name should be?

**Comment by cup** [comment]
Using this file:

~~~
$ curl -L -O \
> https://github.com/nifty-site-manager/nsm/releases/download/v2.0.1/nsm-fix.exe
$ md5sum nsm-fix.exe
bf07feb958bfc27027697bf614adbc90 *nsm-fix.exe
~~~

Fixes the problem:

~~~
$ nsm-fix build-all
successfully tracking sunday
all 3 output files built successfully
time taken: 0.015 seconds
~~~

Still need to work out the PanDoc angle, but wanted to give you an update. Also
I will open separate issues so we can discuss the other topics.

**Comment by cup** [comment]
https://github.com/nifty-site-manager/nsm/issues/17

**Comment by cup** [comment]
https://github.com/nifty-site-manager/nsm/issues/18

**Comment by cup** [comment]
Seems no luck still:

~~~
$ nsm-fix clone https://github.com/nsm-templates/simple-site.git
$ cd simple-site
$ nsm-fix rm about
successfully removed about

$ nsm-fix rm index
successfully removed index

$ mkdir content
$ nsm-fix watch content/ .md
successfully watching directory 'content/' with:
  content extension: '.md'
      template path: 'template/page.template'
   output extension: '.html'

$ echo '# hello' > content/sunday.md
$ echo '@system{inject}("pandoc content/sunday.md")' > template/page.template
$ nsm-fix build-all
successfully tracking sunday
error: content file 'content/sunday.md' has not been used as a dependency within
template file 'template/page.template' or any of its dependencies
~~~

**Comment by n-ham** [comment]
You want `@system{content}(pandoc)`

**Comment by cup** [comment]
No luck:

~~~
$ echo '@system{content}("pandoc")' > template/page.template
$ nsm-fix build-all
[WARNING] Could not deduce format from file extension .md'
   Defaulting to markdown
pandoc: 'content/sunday.md': openBinaryFile: does not exist (No such file or
   directory)
error: 'template/page.template': line 1: @system("pandoc 'content/sunday.md'")
   failed
~~~

Looks like `system` is assuming the users shell is Linux, and using quoting for
that environment.

**Comment by n-ham** [comment]
Just checked that it's working on my machine (though that's linux). One thing is you will also need the `inject` option, and doesn't hurt to add the `!p` option (to not parse the function name, options or parameters) as that scales better (but tbh you don't really need to worry about that unless you have 100k+ pages or something ridiculous like that). 

I'll have a play on Windows and see if I can work out what's going on..

**Comment by n-ham** [comment]
Interestingly you can do `@system{inject}("pandoc @[content-path]")@dep(@[content-path])`, but for some reason on Windows when the content path is quoted (in case it contains spaces) it is not working.

**Comment by cup** [comment]
@n-ham on Windows, PowerShell accepts single or double quoted strings. However Command Prompt (cmd.exe) only accepts double quoted strings, or barewords (if no space or similar).

**Comment by n-ham** [comment]
Powershell seems to throw the same error that Commant Prompt is throwing. I will modify how strings are quoted on Windows and see what happens. Hopefully it doesn't introduce all sorts of other bugs!

**Comment by n-ham** [comment]
I have just uploaded a new `nsm-fix.exe` binary to the github release, the problem seems to be fixed on my Window VM now. Thanks heaps for identifying and reporting all these problems, it really really helps!

**Comment by cup** [comment]
Confirmed fixed! Using this file:

~~~
$ md5sum nsm-fix.exe
067c5027615be2b84509656b54ff8153 *nsm-fix.exe
~~~

and these commands:

~~~
echo '@system{content, inject}(pandoc)' > template/page.template
nsm-fix build-all
~~~

Not sure what you did about the quoting, but it might have been made simpler by
the fact that paths cannot contain double quote characters on Windows, unlike
Linux where paths can contain double and single quote characters. So with
Windows you can probably get away with just wrapping the path in double quotes.

At any rate, I wanted to do at least an extra test, so I tried with a space
`sunday monday.md` and it worked too.

I am going to close this issue, you welcome to reopen if you think its needed.
I would only add that its been fun, but until the Pagination is implemented I
wont be using Nift. This project has great potential, buts thats a needed
feature for me. No hard feelings. Good luck!

**Comment by n-ham** [comment]
Glad that it's fixed, and yep should work no problems with spaces in the file names. Any chance you tried out using pandoc to convert rst as well? Should be no problems there now as well.

I can understand you needing pagination for Nift to be a viable option. I'd like to implement some more of the programming language features first then I will get on to pagination. I'm not sure if that's going to be a week or a month though sorry. I can update you once I have.

**Comment by n-ham** [comment]
I might also change the default behaviour of @system/@script to be that of the `inject` option and require a `console` option for what the current default behaviour is. I feel like people will be using `inject` much more than `console`.

**Comment by cup** [comment]
> Any chance you tried out using pandoc to convert rst as well?

This works as expected:

~~~sh
nsm-fix clone https://github.com/nsm-templates/simple-site.git
cd simple-site
nsm-fix rm about
nsm-fix rm index
mkdir content
nsm-fix watch content/ .rst
echo 'hello
-----' > content/sunday.rst
echo '@system{content, inject}(pandoc)' > template/page.template
nsm-fix build-all
~~~

**Comment by n-ham** [comment]
You should even be able to use Nift's template language in your rst as Nift parses the output from pandoc. However with markdown for example you need to replace `@` with `\@` so it isn't modified while being parsed by pandoc converting to html.
