### ISSUE TITLE
rm doesnt remove content files

### ISSUE THREAD

**Issue by cup** [nifty-site-manager/nsm#15]
> To remove a tracked file run `nsm rm name`. The only difference to untrack is
> that the content file will also be removed from your system.

https://nift.cc/docs/nift_commands#rm

~~~
$ nsm clone https://github.com/nsm-templates/simple-site.git
$ cd simple-site
$ ls content
about.content  index.content

$ nsm rm about
successfully removed about

$ ls content
about.content  index.content
~~~

**Comment by n-ham** [comment]
Hmmm, that must be caused by a bug, it should remove content/about.content with `nsm rm about`. I just tested it on my machine and it's working fine there. 

What operating system are you on? How are you installing Nift? And what version do you have when you run `nsm --version`?

**Comment by n-ham** [comment]
I just remembered from https://github.com/nifty-site-manager/nsm/issues/14 that I'm pretty sure you're on Windows and may be doing this from C:\?

It's possible that nsm doesn't have the privileges to delete files from C:\? I think the desktop should be at like c:\Users\(username)\Desktop so try `cd`'ing to that before cloning, `cd`'ing and running `nsm rm about`. Alternatively if you really want to do it from C:\ and this is the problem when you go to open command prompt you can right click and open it as administrator. 

Have you installed Nift through Chocolatey?

**Comment by n-ham** [comment]
Maybe I should throw an error if Nift fails to remove a file.

**Comment by cup** [comment]
> What operating system are you on?

Windows

> How are you installing Nift?

~~~
curl -L -O \
https://github.com/nifty-site-manager/nsm/releases/download/v2.0.1/nsm.exe
~~~

> And what version do you have when you run nsm --version?

~~~
$ nsm --version
Nift (aka nsm) v2.0.1
~~~

> I think the desktop should be at like `c:\Users\(username)\Desktop` so try
> `cd`ing to that before cloning

~~~
$ cd 'C:\Users\Steven'
$ nsm clone https://github.com/nsm-templates/simple-site.git
$ cd simple-site
$ ls content
about.content  index.content

$ nsm rm about
successfully removed about

$ ls content
about.content  index.content
~~~

**Comment by n-ham** [comment]
Hmm, it looks like there might be a few problems with Windows. I will have a play and get back to you. Sorry about this.

**Comment by n-ham** [comment]
Strange, I thought maybe the way I'm deleting files with C++ doesn't work on windows, but I just tested that with a simple C++ file and it seems to work on Windows no problem.

**Comment by cup** [comment]
> a simple C++ file

I can test that if you want

**Comment by n-ham** [comment]
I have found the bug I'm pretty sure.

It seems you can't do `if(std::ifstream(dir-path))` on Windows to check if a directory exists, that works on unix (at least on linux). 

At least for `rm` and `untrack` etc. I can just check if the file I'm about to remove exists (not sure why I was even checking the directory). I noticed it's also causing a bug with `clone` as well though, so might have to check a few things before putting an updated binary on github.

**Comment by n-ham** [comment]
From https://stackoverflow.com/questions/18100097/portable-way-to-check-if-directory-exists-windows-linux-c I might be able to use

```
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>

int dirExists(const char *path)
{
    struct stat info;

    if(stat( path, &info ) != 0)
        return 0;
    else if(info.st_mode & S_IFDIR)
        return 1;
    else
        return 0;
}
```

**Comment by n-ham** [comment]
I will fix it in the current version I'm working on and then put a copy of the binary for that somewhere you can play with. The new version might not be released for a little bit because I am working on adding programming language features to the template language. I will wrap up some of the stuff I'm working on and try to get out a new release sooner than I was planning to though because these are pretty big bugs on Windows. Thanks a lot for reporting them.

**Comment by n-ham** [comment]
I'm looking forward to checking build times on 10k pages etc. once I finish making these changes because I just checked and this way of checking whether a file exists is like 3 times faster!

**Comment by cup** [comment]
Then even better than Hugo :smiling_imp:

**Comment by n-ham** [comment]
Already more than 3 times faster than Hugo at full builds and up to 15 times faster from having incremental builds, check out https://hugo-vs-nift.gitlab.io/ :)

**Comment by n-ham** [comment]
It's definitely faster, it's hard to say how much though as I've already started adding in programming language features which might have slowed it down a bit on the last version. Thanks to this though the version that comes out with the programming features that should slow it more than anything will be faster than the release before it! Pretty happy about that..

**Comment by cup** [comment]
Glad to hear it, I like the fast and simple nature of this project

**Comment by n-ham** [comment]
I just added `nsm-fix.exe` to the most recent GitHub release. Hopefully that has all the problems fixed for you. I will try to get a few things wrapped up so I can release a new version, most importantly to chocolatey and for people installing from source on Windows.

**Comment by cup** [comment]
confirmed fixed - thanks
