### ISSUE TITLE
2 binaries of the exact same size and source - symlinking?

### ISSUE THREAD

**Issue by ng-0** [nifty-site-manager/nsm#2]
The size of nsm equals the size of nift.
They are built from the same input files.

Was your intention to provide one of them and have the other as a symlink?
If so, do you want the base name as nsm or rather nift?

We can save size with this, unless it matters that they are two names.

**Comment by ng-0** [comment]
It's also a difference to what you describe on the website:

>  Single Executable
>  Nift compiles in to one executable file.

**Comment by n-ham** [comment]
They are indeed 'the same' executable. I originally called it nifty site manager and had the executable as nsm, and still think the executable is better named as nsm as it's very easy to type (I picked the name because it was so easy to type as a command line program). 

I then decided Nift is a much catchier name so have branded it as Nift which it will stay as because I like that. As some people might not read the docs properly or just prefer it, decided to add nift as an executable too. I am open to adding a symlink for nift instead of just compiling it twice, though not sure what to do for windows install then for example? It does seem easier to just compile the two executables so that it's basically the same across linux/osx/windows? Am open to having my mind changed though.

With the website, in my defence it does indeed compile in to one executable but when I install it with the makefile I install two executables. I didn't even think much of that, but a few people have said one of the things they like about other site generators is that there's just one file for the program, so have added it as a selling point for Nift since it's technically correct.

Will leave this open until a decision has been made about the symlink..

**Comment by n-ham** [comment]
I got some Nift stickers from sticker mule and have decided I'll offer to send them out to people who contribute to Nift, whether it be the actual program, or helping make example/template websites, helping work out the best ways to integrate tools/frameworks/libraries/etc. with Nift, helping make tools/frameworks/libraries/plugins/etc. for Nift, etc. etc..

So if you would like me to mail you 5 or so stickers email me an address to contact@n-ham.com

**Comment by ng-0** [comment]
I think there could be a symlink for systems which support it and windows invokes another build hook.

Windows could also get its own Makefile.

**Comment by n-ham** [comment]
Hmmm, I think I'd prefer to just leave it compiling two executables so it's similar between linux/osx/windows. I don't think that matters too much with the selling points on the homepage as you can technically compile Nift in to one executable.

**Comment by n-ham** [comment]
I'm guessing from your organisations that you're an Archer? I suspect Arch users with web development needs will quite like Nift. I posted it on the arch subreddit and the post started taking off like crazy but the mods removed it for not being explicitly about Arch (probably fair enough, but was bummed as would be stoked to find more people with programming and serious unix skills to get on board with making Nift even more awesome).

**Comment by ng-0** [comment]
At 270K for the compiled package in pkgsrc its just nitpicking. I could make it a symlink, but it's not worth the lines of changes and I don't like diverging for maybe 150K.

Many thanks for the offer for stickers :)
I'll send you an email later today.

**Comment by ng-0** [comment]
No, I use almost exclusively NetBSD, but I also use all other systems in my work. pkgsrc a NetBSD project but targeted at cross-systems support.

**Comment by n-ham** [comment]
Let's just leave it as is for the moment then, can revisit it in the future if you or anyone else decides they have a strong opinion about symlinks for whatever reason. 

Ah okay, I've never used NetBSD (or Arch). Have considered trying out Arch, though really like gnome-session-flashback desktop environment with Ubuntu (though I believe you can use the DE with Arch also), plus a lot of solutions to linux problems show up with Ubuntu first in Google even if you don't specify a Distro, one of the reasons I have just stuck with Ubuntu for 10+ years.

**Comment by n-ham** [comment]
6 more stars and can add Nift to homebrew for osx!

**Comment by n-ham** [comment]
Most of the core functionality of Nift is hopefully rock solid, am more than happy to explain various parts of it at some point if you're interested in learning how Nift works fully. 

There's a few things that are trickier than I expected, like writing functions to read paths and system calls for @input(file-path), @systemoutput(system-call), @scriptoutput(script-path) etc.. And there's no way to inject say the page name of the page being built in to the file-path/system-call/script-path etc. which I am considering trying to work out a good way to add in, though also don't really see any use cases for it so am not prioritising it too much. 

One thing I am planning to add in soon is @inputhead syntax which will inject a page-name.head file in that place if it exists, similar to @inputcontent which injects page-name.content in that place (@inputcontent has to be present in the template file or one of the files it inputs, and the content file must exist for all pages, whereas @inputhead will be optional and even if it's present will be optional for page-name.head to exist), this will make it possible to easily add custom head code for individual pages that is different to what's in the head for the template.

**Comment by ng-0** [comment]
are you sure that you need stars? we have a project which operates within its own infrastructure but distributes via ftp.gnu.org and someone of us managed to get it into homebrew regardless of an almost completely ignored github read-only mirror

**Comment by n-ham** [comment]
Hmmm, I just saw it on their site that they like 75 stars on GitHub amonst a few other things, so figured I'd aim for that before trying to add it. Maybe I should just try and add it anyway. I also had trouble trying to figure out how to package Nift for homebrew, have you packaged anything for Homebrew yourself before?

**Comment by ng-0** [comment]
No, my experience with Apple using products is limited to what translates to highschool many years back and even further back an Apple II or whatever it was.
This is the inofficial formula: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gnunet.rb While we support many more configure switches it looks pretty doable.

**Comment by n-ham** [comment]
Am going to try and figure out Docker at some point too, as someone suggested that should make it possible to use Nift with GitHub actions to trigger a rebuild whenever people push changes to a site repository. (Though will only work when both stage and site files are all in the one branch like with the GitLab templates, not the BitBucket/GitHub templates). 

Might have already mentioned, but in talks with Netlify to get Nift added to their build-image, then you will be able to trigger a rebuild when changes are pushed to repo on BitBucket, GitHub or GitLab. Which is also useful for triggering a rebuild when people make changes to content through a CMS.

**Comment by bkmgit** [comment]
A symlink is helpful. Will make a pull request for linux.
