### ISSUE TITLE
Remove .html from url

### ISSUE THREAD

**Issue by tatimblin** [nifty-site-manager/nsm#20]
Right now the site is outputted as 
```
root/
-- 404.html
-- about.html
-- index.html
```

Can it instead output into folders like
```
root/
-- 404/
---- index.html
-- about/
---- index.html
-- index.html
```
This could be a flag in `nift.config`, but I don't think including the `.html` file path would be a desired output

**Comment by n-ham** [comment]
I will see if I can add a flag in nift.config to do this. Someone else requested being able to change the output path for a page too so that might be another way to do it as well.

**Comment by n-ham** [comment]
There are also implications for things like `@pathto(name)` that need to be fleshed out for this to work. Obviously if you have `about/index.html` you probably want `@pathto(about)` to give the path to `about/` and not the path to `about/index.html`?

**Comment by tatimblin** [comment]
Hey @n-ham I realized the other day I got all these great replies from you and didn't say anything back. I wanted to thank you for helping me understand your project, no doubt Nift is going to be great.
I tend to have a problem of continuously rebuilding my projects trying to perfect them, without ever finishing. This time I'm committed to finishing, so I've decided to move forward a stack I'm more familiar with. BUT I think Nift could help make it better so if I do finish I'll be back.
Thanks and good luck!

**Comment by n-ham** [comment]
Hey @tatimblin, thanks for the comment. Totally understand going with a stack you're more familiar with. I have been working away very hard and the programming languages that I've implemented I'm really really happy with, they're far better than I expected when I started implementing some basic features. I've also found a c++ library for parsing and evaluating mathematical expressions which is super fast and has nicer syntax for stuff like logical operators, maths expressions etc. etc.. Nift will soon come with the ability to run scripts in three languages (you can use all three languages in content/template files for website building) and shells you can use for two of those languages. 

The shells are much faster than bash for example (and you can easily just run commands from the shell you're running the nift shell(s) from), and the math expression parser library I found will put most aspects of the scripting languages in the leagues of languages like python and ruby I think/hope. 

Let me know if you're interested in exploring Nift again in the future and am happy to hear what you're doing and give advice on the best way to use Nift for it.
