### ISSUE TITLE
Nift sh has stopped working for me

### ISSUE THREAD

**Issue by emilyanncr** [nifty-site-manager/nsm#32]
I use Nift to make the text in my terminal rainbox. Used to work without issue. But now when I do nift sh it says "cannot change profile for the next exec call: No such file or directory".  Can you please advise?  Super cool project btw.

**Comment by n-ham** [comment]
Hey there, sorry have been a bit flat out.. It might have something to do with how Nift was installed?

**Comment by emilyanncr** [comment]
hmm
