### ISSUE TITLE
[feature request] Nift as a static/shared library

### ISSUE THREAD

**Issue by NuLL3rr0r** [nifty-site-manager/nsm#6]
It would be great if Nift provides a way to be built as a static/shared library. I have an upcoming project in C++ which is intended to be used by non-technical people with an easy to use GUI and I am thinking of embeding a static generator into it for part of its functionality.

Is it possible at all?

**Comment by n-ham** [comment]
Sorry for my lack of knowledge, what does/doesn't count as a static/shared library? Does that mean you can basically include it in the project like headers and use it like that? As I suspect that'd take a huge amount of work with Nift unfortunately, something I'm unlikely to find the time to do any time soon.

What you could do is use system calls to run the site generator (if you're only having to make one system call each time build is run it should still be perfectly fast). Nift compiles in to a single binary/executable so it's easy to just use a system call to interact with Nift? Would that be an acceptable solution? You could do similarly with other website generators, but Nift is the fastest, can handle millions of websites and has the systemoutput/scriptoutput functionality etc.. 

Would be cool to see some kind of GUI proect that uses Nift as part of its functionality.

**Comment by NuLL3rr0r** [comment]
Well, this is going to be CMS for a news website. I thought instead of putting the database on the server and write backend/frontend for it, why not just write a desktop application that generates the output as static HTML (basically a customized graphical static generator for non-tech-savvy users).

Yes, I thought of invoking Nift by doing system calls, that definitely works. Although it is going to be a bit dirty, slower, and less flexible for my use-case since I am not going to render the whole website all at once as the user works on one page at a time. Maybe my best bet would be integrating a markdown library and instead write the whole logic in my own app.

**Comment by n-ham** [comment]
It's a fair bit of work to write the engine for a site generator. I wouldn't want to do it all over again. I ran some tests the other day and could do 10k system calls in under 10 seconds, so should be able to run build-updated every 0.5 seconds or whatever using system calls without any real drama. 

You can add live server/reload in to pre/post build/serve scripts with Nift for hot reloading, which sounds like it might be useful for what you're planning.

**Comment by NuLL3rr0r** [comment]
Thanks, I guess hot-reloading would work too. I am in the early stages and haven't started the development yet. So, I'll consider that. Thank you again!

**Comment by n-ham** [comment]
If you do decide to try using Nift for this let me know as I'm happy to answer questions to help make it easier to figure out.

**Comment by NuLL3rr0r** [comment]
Sure, thanks!

**Comment by n-ham** [comment]
Did you end up working on this project at all? I wonder whether we could make some kind of library file for Nift.. Or how slow it would be to just have the gui interact with Nift using system calls for example..

**Comment by NuLL3rr0r** [comment]
Unfortunately, not yet. But, let you know if it happens.
